Proyecto Pair Programming/force-app/main/default/objects/Module__c.object
<CustomObject>
    <fields>
        <fullName>Points__c</fullName>
        <label>Points</label>
        <summaryForeignKey>Unit__c.Module__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>TotalTime__c</fullName>
        <label>TotalTime</label>
        <summaryForeignKey>Unit__c.Module__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>Module</label>
    <nameField>
        <label>Module Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Modules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Proyecto Pair Programming/force-app/main/default/objects/Options__c.object
<CustomObject>
    <fields>
        <fullName>Content__c</fullName>
        <label>Content</label>
        <length>66255</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Question__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Question</label>
        <referenceTo>Question__c</referenceTo>
        <relationshipLabel>Options</relationshipLabel>
        <relationshipName>Options</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Option</label>
    <nameField>
        <label>Options Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Options</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Proyecto Pair Programming/force-app/main/default/objects/Question__c.object
<CustomObject>
    <fields>
        <fullName>Content__c</fullName>
        <label>Content</label>
        <length>131070</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Unit__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Unit</label>
        <referenceTo>Unit__c</referenceTo>
        <relationshipLabel>Questions</relationshipLabel>
        <relationshipName>Questions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Question</label>
    <nameField>
        <label>Question Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Proyecto Pair Programming/force-app/main/default/objects/Trail__c.object
<CustomObject>
    <label>Trail</label>
    <nameField>
        <label>Trail Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trails</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Proyecto Pair Programming/force-app/main/default/objects/TrailModule__c.object
<CustomObject>
    <fields>
        <fullName>Module__c</fullName>
        <label>Module</label>
        <referenceTo>Module__c</referenceTo>
        <relationshipName>TraiModules</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Points__c</fullName>
        <label>PointsTrailModule</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Trail__c</fullName>
        <label>Trail</label>
        <referenceTo>Trail__c</referenceTo>
        <relationshipName>TraiModules</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>TrailModule</label>
    <nameField>
        <label>TrailModule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TrailModules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Proyecto Pair Programming/force-app/main/default/objects/Unit__c.object
<CustomObject>
    <fields>
        <fullName>Content__c</fullName>
        <label>Content</label>
        <length>131071</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Module__c</fullName>
        <label>Module</label>
        <referenceTo>Module__c</referenceTo>
        <relationshipLabel>Units</relationshipLabel>
        <relationshipName>Units</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Points__c</fullName>
        <label>Points</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Time__c</fullName>
        <label>Time</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Unit</label>
    <nameField>
        <label>Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Units</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Proyecto Pair Programming/force-app/main/default/objects/UserModule__c.object
<CustomObject>
    <fields>
        <fullName>Module__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Module</label>
        <referenceTo>Module__c</referenceTo>
        <relationshipLabel>UserModules</relationshipLabel>
        <relationshipName>UserModules</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipLabel>UserModules</relationshipLabel>
        <relationshipName>UserModules</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>UserModule</label>
    <nameField>
        <label>UserModule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>UserModules</pluralLabel>
    <recordTypes>
        <fullName>UserModule</fullName>
        <active>true</active>
        <label>UserModule</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

Proyecto Pair Programming/force-app/main/default/objects/UserQuestion__c.object
<CustomObject>
    <fields>
        <fullName>Question__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Question</label>
        <referenceTo>Question__c</referenceTo>
        <relationshipLabel>UserQuestions</relationshipLabel>
        <relationshipName>UserQuestions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>UserUnit__c</fullName>
        <label>UserUnit</label>
        <referenceTo>UserUnit__c</referenceTo>
        <relationshipLabel>UserQuestions</relationshipLabel>
        <relationshipName>UserQuestions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>UserQuestion</label>
    <nameField>
        <label>UserQuestion Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>UserQuestions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Proyecto Pair Programming/force-app/main/default/objects/UserUnit__c.object
<CustomObject>
    <fields>
        <fullName>Points__c</fullName>
        <label>Points</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Answered</fullName>
                </value>
                <value>
                    <fullName>Success</fullName>
                </value>
                <value>
                    <fullName>Fail</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Unit__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Unit</label>
        <referenceTo>Unit__c</referenceTo>
        <relationshipLabel>UserUnits</relationshipLabel>
        <relationshipName>UserUnits</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>UserModule__c</fullName>
        <label>UserModule</label>
        <referenceTo>UserModule__c</referenceTo>
        <relationshipLabel>UserUnits</relationshipLabel>
        <relationshipName>UserUnits</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>UserUnit</label>
    <nameField>
        <label>UserUnit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>UserUnits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Proyecto Pair Programming/force-app/main/default/classes/UnitService.cls
public with sharing class UnitService {

    @AuraEnabled(cacheable = false)
    public static Boolean getUnitIds(Id unitId, String jsonAnswer) {

        // parseamos el jsonAnswer a un map.
        Map<Id, Id> questionsMap = (Map<Id, Id>) JSON.deserializeStrict(jsonAnswer, Map<Id, Id>.class);

        //Tengo un list que almacena los ids de mis options(respuestas de mis preguntas en list questions).
        List<Options__c> options = New List<Options__c>();


        //busco la unidad con el id "unitId" en la base de datos
        Unit__c unit = [SELECT module__c FROM Unit__c WHERE Id=:unitId];
        //busco el modulo relacionado con el id de unidad asociados al usuario, si no existe , signfica que es la primera pregunta , creo el UserModule
        //veo si existe el userModule , sino lo creo
        //uso userInfo.getUserId() para obtener el id del usuario actual
        UserModule__c module;
        try{
            module = [SELECT Id FROM UserModule__c WHERE Module__c = :unit.Module__c  AND User__c = :UserInfo.getUserId() AND Status__c = 'In Progress'];
            }catch (Exception e){

            module = new UserModule__c(User__c = userInfo.getUserId(),
            Module__c = unit.Module__c,
            Status__c = 'In Progress');
            insert module;
           } 
        //creo el UserUnit en estado draft
        UserUnit__c unitResp = new UserUnit__c(
            Unit__c = unitId,
            UserModule__c = module.Id,
            State__c = 'Draft',
            User__c = UserInfo.getUserId()
          );

          //Tengo un list que almacena los ids de mis questions.
        List<UserQuestion__c> questions = New List<UserQuestion__c>();

          for(Id q : questionsMap.keySet()) {
            // Código a ejecutar para cada key del mapa
            UserQuestion__c questionKey = new UserQuestion__c(Unit__c=unitId, Question__c=q);

            questions.add(questionKey);
        }

        unitResp.State__c = 'Answered';

        insert questions;

        update unitResp;

        // ATENCION --- Quizás deba hacer otra query para traerme el unitResp actualizado a Success.

        if(unitResp.State__c == 'Success'){
            return true;
        }else{
            return false;
        }
    }

    @AuraEnabled(cacheable = false)
    public static TrailWrapper getTrailWrapper(Id trailId) {
        TrailWrapper wrapper = new TrailWrapper();
        
        wrapper.trail = [SELECT Name, Description__c
                 FROM Trail__c 
                 WHERE Id = :trailId];
        
        // Obtener los registros de TrailModule__c que están relacionados con el trailId dado
        List<TrailModule__c> trailModules = [SELECT Module__c FROM TrailModule__c WHERE Trail__c = :trailId];

        List<Id> moduleIds = new List<Id>();
        for (TrailModule__c tm : trailModules) {
            moduleIds.add(tm.Module__c);
        }

        // Obtener los módulos relacionados a través de la relación Module__c en los registros de TrailModule__c
        //List<Module__c> modules = [SELECT Id, Name, Description__c FROM Module__c WHERE Id IN :moduleIds];
        List<Module__c> modules = [SELECT Id, Name, Description__c, Points__c, TotalTime__c, (SELECT Id, Name, Time__c, Points__c FROM Units__r) FROM Module__c WHERE Id IN :moduleIds];
        wrapper.modules = modules;

        List<UserUnit__c> userUnits = [SELECT Id, State__c, Unit__c FROM UserUnit__c WHERE Unit__c IN (SELECT Id FROM Unit__c WHERE Module__c IN :modules) AND User__c = :UserInfo.getUserId() AND State__c = 'Success'];

        Set<Id> passedModuleIds = new Set<Id>();
        Set<Id> passedUnitIds = new Set<Id>();

        // Iterar por los registros de UserUnit__c para obtener los módulos y unidades aprobadas
        for (UserUnit__c userUnit : userUnits) {
            passedModuleIds.add(userUnit.Unit__r.Module__c); // Agregar el Id del módulo aprobado al conjunto de passedModuleIds
            passedUnitIds.add(userUnit.Unit__c); // Agregar el Id de la unidad aprobada al conjunto de passedUnitIds
        }

        wrapper.passedModuleIds = passedModuleIds;
        wrapper.passedUnitIds = passedUnitIds;
    
        wrapper.progressTrail = Math.round((100.0 * passedUnitIds.size()) / wrapper.modules.size());
       
        return wrapper;
    }

    @AuraEnabled(cacheable = false)    
    public static UnitWrapper getUnitWrapper(Id unitId) {
        UnitWrapper wrapper = new UnitWrapper();
    
        // Query for Unit__c record and populate wrapper.unit
        wrapper.unit = [SELECT Id, Name, Time__c, Points__c, Content__c  FROM Unit__c WHERE Id = :unitId];

        // Query for related Question__c records and their related Options__c records and populate wrapper.questions
        wrapper.questions = [SELECT Id, Name, Content__c, (SELECT Id, Name, Content__c FROM Options__r) FROM Question__c WHERE Unit__c =: unitId];
    
        return wrapper;
    }
}